# Generated by Django 3.0.2 on 2020-01-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencemodel',
            name='state',
            field=models.TextField(blank=True, default='POR_VALIDAR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='occurrencemodel',
            name='updated_date',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
